###
# Swiftlint configuration file.
# Latest version supported: 0.16.1
# Any newer version hasn't been checked yet and might not follow the style guide.
#
# To update your local version of this file, execute the following command line:
# curl https://raw.githubusercontent.com/kevindelord/swift-style-guide/master/.swiftlint.yml > .swiftlint.yml
###

disabled_rules: # Rule identifiers to exclude from running
  - colon # Exaclty one space after the : >>> let abc: Void\n
  - control_statement # No rounded brackets around conditions. we would need this the other way around
  - todo # TODO can be written in the code but should be linked to a ticket on JIRA.
  - nesting # Func nesting max 1 level
  - cyclomatic_complexity # Limit the number of entries inside an enum or struct.
  - unused_closure_parameter
  - empty_parentheses_with_trailing_closure
  - closure_parameter_position
  - redundant_string_enum_value
  - trailing_whitespace

excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - RxHTTPClient
  - Example

# rule parameters
file_length:
  - 800 #warning
  - 1000 #error

function_body_length:
  - 60 #warning
  - 80 #error

line_length:
  - 120 #warning
  - 140 #error

type_body_length:
  - 400 #warning
  - 500 #error

large_tuple:
  - 4 #warning
  - 6 #error

allow_private_set:
 - allow_private_set: true

opt_in_rules:
  - conditional_returns_on_newline
  - private_outlet
  - vertical_whitespace
  - closure_spacing
  - explicit_init
  - redundant_nil_coalescing
  - nimble_operator
  - attributes
  - closure_end_indentation
  - empty_count
  - large_tuple
  - function_parameter_count

